### ISSUE TITLE
"Couldn't Copy link to clipboard." shows, while actually working perfectly

### ISSUE THREAD

**Issue by SimJoSt** [Dreamcooled/sjupdater#39]
A click on a hoster causes the program to freeze for a few seconds, then showing the error message while unfreezing.
At the same time a clipboard-monitor recognizes the link immediately without any problem.

**Comment by Dreamcooled** [comment]
Hei @SimJoSt,
I have heard of that before. 

But I'm not sure if it's an issue with SjUpdater.
Could you try if the error still occours if you run SjUpdater as Admin?
What clipboard-monitor are you using? Jdownloader?
If I'm able to reproduce the bug on my side, I can look into it. Otherwise it's a bit difficult. Please provide me with some more info.

The Code that I use on my end is really simple:
```
for (int i = 0; i < 10; i++)
{
	try
	{
		Clipboard.SetText(linkstring);
		Clipboard.Flush();
		return;
	}
	catch
	{
		//nah
	}
	Thread.Sleep(10);
}
MessageBox.Show("Couldn't Copy link to clipboard.\n" + linkstring);
```

**Comment by SimJoSt** [comment]
The problem doesn't occur every time, but when it does the next time, i will try you proposition.
I am running Windows 8.1 64bit with the newest updates installed. It's an older and slow system. I don't have any other indications.

**Comment by Dreamcooled** [comment]
Ok. When it does occour the next time: Check what other applications are running. Sometimes a third party app is causing the trouble.
Also, since you're using win8: Do you have any problems with the notify icon? #33

**Comment by SimJoSt** [comment]
I've been using the program regularly and the error didn't occur anymore at all.

**Comment by Dreamcooled** [comment]
Ok. Several users are reporting this problem occasionally from time to time.
What helped is asking them if they installed any tools which monitor the clipboard (like "FreeDownloadManager"). Closing those tools normally solved the problem.
